stages:
- build
- publish

before_script:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm ci

build:
  stage: build
  image: node:14
  only:
  - master
  - develop
  script:
  - npm run lint
  - npm run build
  - npm run test

publish:
  stage: publish
  image: node:14
  only:
  - tags
  script:
  - npm run lint
  - npm run build
  - npm run test
  - npm --no-git-tag-version version ${CI_COMMIT_TAG}
  - npm publish --non-interactive --access public
  variables:
    NPM_TOKEN: ${NPM_TOKEN}
